# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Votr' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Votr
  pod 'ProgressHUD'
  pod 'ASJTagsView'
  pod 'SCLAlertView-Objective-C'
  pod 'TTTAttributedLabel'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
end
