# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Votr' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Votr
  pod 'ProgressHUD'
  pod 'SCLAlertView-Objective-C'
  pod 'TTTAttributedLabel'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Invites'
  pod 'Firebase/DynamicLinks'
  pod 'GoogleSignIn'
  pod 'Firebase/Database'
  pod 'FirebaseUI', '~> 1.0'
  pod 'JVFloatLabeledTextField'
  pod 'WSTagsField'
  pod 'FLAnimatedImage', '~> 1.0'
  pod 'LLSimpleCamera', '~> 4.1'
  pod 'JLRoutes'
end
